server:
  port: 8010
spring:
  application:
    name: provider  #当前服务注册在eurekaServer的名字   微服务的名字
eureka:
  client:
    service-url: #注册中心的访问地址
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true  #是否将当前服务的IP地址注册到EurekaServer